name: CI

on:
  push:
    branches:
      - main  # Change to your default branch if necessary
  pull_request:
    branches:
      - main  # Change to your default branch if necessary

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    services:
      docker:
        image: docker:19.03.12  # Use a specific Docker version
        options: >-
          --privileged  # Run Docker in privileged mode
          --network host  # Use host networking

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Check out the repository code

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1  # Set up Docker Buildx

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub username
          password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub password

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./app/LabApp_Docker_Leistungsnachweis  # Context for the build
          file: ./app/LabApp_Docker_Leistungsnachweis/Dockerfile  # Path to the Dockerfile
          tags: your-dockerhub-username/cloud-app:latest  # Change to your Docker Hub username and image name

      - name: Run tests
        run: |
          docker run --rm your-dockerhub-username/cloud-app:latest ./run_tests.sh  # Adjust to your test command

